
build_dir:
  specfempp: "/scratch/gpfs/rk9481/specfem2d_kokkos/build"
  specfem2d: "/scratch/gpfs/rk9481/do_not_change/benchmarks/cpu/specfem2d"

resources:
  cpu:
    nodes: 1
    tasks: 1
    cpus_per_task: 1
    runtime: 10
    mem_mb_per_cpu: 10000
    constraint: skylake
    slurm_extra: ""

description:
  benchmark_1: "Elastic domain"
  benchmark_2: "Acoustic domain"
  benchmark_3: "Elastic-acoustic domain"

benchmarks:
  benchmark_1:
    cpu:
      simulation_1:
        nx: [1, 80]
        nz: [1, 60]
      simulation_2:
        nx: [1, 160]
        nz: [1, 120]
      simulation_3:
        nx: [1, 320]
        nz: [1, 240]
      simulation_4:
        nx: [1, 640]
        nz: [1, 480]
      simulation_5:
        nx: [1, 1280]
        nz: [1, 960]

  benchmark_2:
    cpu:
      simulation_1:
        nx: [1, 160]
        nz: [1, 120]
      simulation_2:
        nx: [1, 320]
        nz: [1, 240]
      simulation_3:
        nx: [1, 640]
        nz: [1, 480]
      simulation_4:
        nx: [1, 1280]
        nz: [1, 960]
      # simulation_5:
      #   nx: [1, 2560]
      #   nz: [1, 1920]

  benchmark_3:
    cpu:
      simulation_1:
        nx: [1, 144, 1, 144]
        nz: [1, 54, 55, 108]
      simulation_2:
        nx: [1, 288, 1, 288]
        nz: [1, 108, 109, 216]
      simulation_3:
        nx: [1, 576, 1, 576]
        nz: [1, 216, 217, 432]
      simulation_4:
        nx: [1, 1152, 1, 1152]
        nz: [1, 432, 433, 864]
      # simulation_5:
      #   nx: [1, 2304, 1, 2304]
      #   nz: [1, 864, 865, 1728]
    